### ISSUE TITLE
Support for no_std

### ISSUE THREAD

**Issue by ERROR-PC** [chuckcscccl/fixedstr#2]
Add a feature for "std", then add #![no_std] at the crate root.
Now you conditionally compile certain pieces of code (like printing) under a #[cfg(feature = "std")], and enable the std feature by default for convenience. This way both std and no_std environments are supported

**Comment by chuckcscccl** [comment]
This will be available in the next release

**Comment by chuckcscccl** [comment]
version 0.4.0 now supports no_std as an option
