### ISSUE TITLE
Compile error on crate alloc with no-alloc feature enabled

### ISSUE THREAD

**Issue by Malphaet** [chuckcscccl/fixedstr#5]
The line https://github.com/chuckcscccl/fixedstr/blob/ea7c149693caafa467a1c387f827a9d7f92ecf10/src/zero_terminated.rs#L29 causes the following compile time error on a no-std, no-main, no-alloc (arduino) environement:
```
   Compiling fixedstr v0.5.2
error[E0463]: can't find crate for `alloc`
  --> /home/dandaedre/.cargo/registry/src/index.crates.io-6f17d22bba15001f/fixedstr-0.5.2/src/zero_terminated.rs:29:1
   |
29 | extern crate alloc;
   | ^^^^^^^^^^^^^^^^^^^ can't find crate
```

Preposing it with `#[cfg(not(feature = "no-alloc"))]` solves this issue for me

**Comment by chuckcscccl** [comment]
Yes, that line should be there.  The error did not show up in my build environment.
This has been fixed in Version 0.5.3
