### ISSUE TITLE
zstrs don't pad in format!()

### ISSUE THREAD

**Issue by notak** [chuckcscccl/fixedstr#6]
Adding padding to a fmt definition doesn't lead to a zstr being padded, as happens for str. The relevant code for str is:

```rust
#[stable(feature = "rust1", since = "1.0.0")]
impl Display for str {
    fn fmt(&self, f: &mut Formatter<'_>) -> Result {
        f.pad(self)
    }
}
```

so I guess this could probably be resolved by changing

https://github.com/chuckcscccl/fixedstr/blob/45e84432ded726c9dd019bc862c7508d3bab2d83/src/zero_terminated.rs#L611

to:

```rust
  f.pad(self.to_str())
```

**Comment by chuckcscccl** [comment]
Change has been made in version 0.5.4 to zstr (and other types)
